/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.jakarta.persistence.jakarta.persistence.api)
    api(libs.org.springframework.spring.context)
    api(libs.org.springframework.spring.tx)
    api(libs.org.springframework.data.spring.data.commons)
    api(libs.org.yaml.snakeyaml)
    api(project(":skillhub-storage"))
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.org.hibernate.orm.hibernate.core)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "skillhub-domain"
