/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":skillhub-domain"))
    api(project(":skillhub-infra"))
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.spring.context)
    api(libs.io.github.arbing.jieba.analysis)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "skillhub-search"
