/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("org.springframework.boot") version "3.2.3"
    id("io.spring.dependency-management") version "1.1.4"
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    api(project(":skillhub-domain"))
    api(project(":skillhub-auth"))
    api(project(":skillhub-infra"))
    api(project(":skillhub-search"))
    api(project(":skillhub-notification"))
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.flywaydb.flyway.core)
    api(libs.org.flywaydb.flyway.database.postgresql)
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    api(libs.org.springframework.session.spring.session.data.redis)
    api(libs.org.redisson.redisson)
    runtimeOnly(libs.org.postgresql.postgresql)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    testImplementation(libs.com.h2database.h2)
}

description = "skillhub-app"


tasks.named<Jar>("jar") {
    enabled = false
}

tasks.named("bootJar") {
    (this as org.gradle.api.tasks.bundling.Jar).archiveFileName.set("skillhub-app.jar")
}
