/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "skillhub-parent"
include(":skillhub-storage")
include(":skillhub-auth")
include(":skillhub-infra")
include(":skillhub-search")
include(":skillhub-app")
include(":skillhub-domain")
include(":skillhub-notification")
