/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":skillhub-domain"))
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.data.redis)
    api(libs.org.springframework.boot.spring.boot.starter.mail)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "skillhub-auth"
