/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":skillhub-domain"))
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "skillhub-notification"
