/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter)
    api(libs.org.yaml.snakeyaml)
    api(libs.software.amazon.awssdk.s3)
    api(libs.software.amazon.awssdk.apache.client)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
}

description = "skillhub-storage"
